### ISSUE TITLE
How to add "rename" to the file explorer treeview

### ISSUE THREAD

**Issue by dehilsterlexis** [microsoft/vscode-extension-samples#349] opened 2020-10-09 14:46 UTC
VSCode allows you to click on a file and choose "rename" in the context menu. It then highlights the item and allows you to type in a new name. Can this be used in the treeview? If so, how?

**Comment by isidorn** [comment] 2021-07-26 12:14
Forwarding to @alexr00 since I think she owns the custom trees. 
I have no plans of action here.

**Comment by alexr00** [comment] 2021-07-26 12:18
duplicate of https://github.com/microsoft/vscode/issues/97190

**Closed by alexr00** 2021-07-26 12:18 UTC
