### ISSUE TITLE
fsprovider-sample: "no provider for memfs:/"

### ISSUE THREAD

**Issue by jens-duttke** [Microsoft/vscode-extension-samples#68] opened 2018-05-16 09:57 UTC
I've installed the MemFS extension in VSCode 1.23.1 and get this error if I try to setup a workspace:
`no provider for memfs:/`

**Comment by jrieken** [comment] 2018-05-16 12:46
> and get this error if I try to setup a workspace:

How exactly are you doing that?

**Comment by jrieken** [comment] 2018-05-17 07:51
> Btw. I'm using Windows 7, a colleague who is using MacOS does not have this problem. Maybe this is the source of the problem?

Hm, maybe some backslash vs fwdslash challenges...

>  "[Error] TypeError: Cannot read property ‘uri’ of undefined", if he Setup the Workspace, if an Workspace is already open.

What? You shouldn't even see the command when a workspace is open...

**Comment by jrieken** [comment] 2018-05-17 14:29
adding @isidorn for the stale markers

**Comment by jens-duttke** [comment] 2018-05-18 06:11
Ok, I checked that again:

1. in VSCode of my colleague an folder was open - but not a workspace. That's why it showed the command to setup the workspace.
If he close the folder before he setup the workspace, the "TypeError: Cannot read property ‘uri’ of undefined" error does not occur.

2. Currently I'm developing my own extension (based on the fsprovider-sample) - there, I got the error first (for sure, with my own schema name).
To see if this problem also occurs in the fsprovider-sample or if I did something wrong, I've installed the MemFS extension - but in the debug-session of my extension in VSCode. The problem was the same.
If I use the extension in the "normal" VSCode (not in the debug session), it works without problems.

Sorry for the confusion.

**Comment by jens-duttke** [comment] 2018-05-18 10:08
To me it looks like the registration of the file system provider works async and takes up to 5 seconds to initialize.
If the memfs.workspaceInit command is executed, the activate method is called the first time, which then registers the file system provider and directly after that, calls vscode.workspace.updateWorkspaceFolders in the method, which is assigned to the memfs.workspaceInit command. This produces the "no provider for memfs:/" error, because at this moment, the file system provider is not initialized.
About 5 seconds later activate is called again, because of the onFileSystem activation event - from now on, the file system schema can be used.

**Comment by jonathangraf** [comment] 2018-05-18 11:36
I also get this error when trying this. I work on MacOS.
My steps to install:

I downloaded the folder as a ZIP

Unzipped it and opened /fsprovider-sample as a folder in VS Code

I started the debug mode
![bildschirmfoto 2018-05-18 um 13 31 30](https://user-images.githubusercontent.com/39404597/40232616-d0bb3ee2-5a9f-11e8-8f1e-0decbf448942.png)

Now I try to setup a new workspace (via F1 and typing `MemFS: Setup Workspace`) and then I get the following error message:
![bildschirmfoto 2018-05-18 um 13 30 05](https://user-images.githubusercontent.com/39404597/40232565-9a936380-5a9f-11e8-8044-ac12482de234.png)

And it creates an empty folder
![bildschirmfoto 2018-05-18 um 13 30 58](https://user-images.githubusercontent.com/39404597/40232598-ba76e866-5a9f-11e8-9697-2118cb866f7d.png)

**Comment by jrieken** [comment] 2018-06-06 09:27
We got to the bottom of this. Closing as duplicate of https://github.com/Microsoft/vscode/issues/51088

**Closed by jrieken** 2018-06-06 09:27 UTC
