### ISSUE TITLE
webView example no longer works in remote

### ISSUE THREAD

**Issue by benc-uk** [microsoft/vscode-extension-samples#219] opened 2019-10-11 06:42 UTC
The JS file is never loaded, this error is thrown
```
Unable to read file (Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"))
    at v.readFileStream (file:///C:/Users/becolem/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1539:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Issue is reproducible in WSL remote and SSH

Note the cat GIF loads OK, as that's an external HTTP URL, but the JS file referenced from the extension (media directory) doesn't load due to the above error, so the line counter never goes up

I suspect the issue is caused by the remote extension(s). Issue here
https://github.com/microsoft/vscode-remote-release/issues/1643

**Comment by mjbvz** [comment] 2019-10-14 21:24
Duplicate of https://github.com/microsoft/vscode/issues/82336

**Closed by mjbvz** 2019-10-14 21:24 UTC
