### ISSUE TITLE
Where is the "vscode-install" script?

### ISSUE THREAD

**Issue by brian-pickens-web** [microsoft/vscode-extension-samples#120] opened 2018-11-13 17:50 UTC
Trying to base my own project off of the lsp-sample project, however I get the following error:
```
'vscode-install' is not recognized as an internal or external command,
operable program or batch file.
```
Which is used in the client and server package.json scripts section same as in the lsp-sample. Where do these come from and do I need them?

**Comment by octref** [comment] 2018-11-26 20:02
They are defined here: https://github.com/Microsoft/vscode-extension-vscode/blob/master/package.json. It used to be `node ./node_modules/vscode/bin/install`.

This does not fail for me though. Are you running `npm install` at the root level of the sample?

**Comment by mjbvz** [comment] 2019-05-10 00:10
Closing as we've updated most samples to use `@types/vscode` instead, which does not require the post install script

**Closed by mjbvz** 2019-05-10 00:10 UTC
Labels: needs more info

**Comment by Razzeee** [comment] 2019-08-27 10:03
the language server example still has that `vscode-install` call

**Comment by dbaeumer** [comment] 2019-08-28 09:52
The sample still uses vscode since it uses a special form of test running. `vscode-install` is in the `node_modules/.bin`

**Comment by Razzeee** [comment] 2019-08-28 09:55
So it should not be "upgraded"?

I changed that for my LSP and the release build crashed with an error pointing to it missing the "request" lib. Not sure if that's really caused by this, but felt like I should point it out.

**Comment by dbaeumer** [comment] 2019-08-29 07:45
The new @types / vscode-test does work for me for the LSP libraries. You might want to have a look here: https://github.com/microsoft/vscode-languageserver-node/commit/f6b2f0e523629b85055cc940ab1d6204d636d1f1
