### ISSUE TITLE
webview-view-sample: Mutiple webview in views get position error

### ISSUE THREAD

**Issue by HuyQLuong** [microsoft/vscode-extension-samples#462] opened 2021-07-12 17:47 UTC
From  webview-view-sample

I have add 2 more webview to views by  `registerWebviewViewProvider` 

```
context.subscriptions.push(
		vscode.window.registerWebviewViewProvider(ColorsViewProvider.viewType, provider));
	
context.subscriptions.push(
		vscode.window.registerWebviewViewProvider(ColorsViewProvider.viewType1, provider));

context.subscriptions.push(
		vscode.window.registerWebviewViewProvider(ColorsViewProvider.viewType2,provider));
```

Then declare on `package.json`
![image](https://user-images.githubusercontent.com/42475309/125332672-865e4000-e373-11eb-8899-80a8e908e834.png)

Result I get from expand and fold the view

https://user-images.githubusercontent.com/42475309/125332889-c9b8ae80-e373-11eb-8561-cdea90308fed.mov

Expected:

When I expand and fold the view,  the position should be re-calculated

**Comment by mjbvz** [comment] 2021-07-13 01:18
Duplicate of https://github.com/microsoft/vscode/issues/110450

**Closed by mjbvz** 2021-07-13 01:18 UTC
