### ISSUE TITLE
virtual-document-sample is too complicated

### ISSUE THREAD

**Issue by MegaMech** [microsoft/vscode-extension-samples#666] opened 2022-06-21 07:08 UTC
Can the cow stuff be removed along with "ShowInputBox"

This sample should only open a TextDocument that contains a few words of text and that's it. The way it's crafted makes it much harder to follow what's going on and how the uri interacts with the various elements.

Specifically, the function "say" in the .d.ts file conflicts with the package.json's cow.say namings which then conflicts with "cowsay"

Cows are cool. Naming confusion is not.

The main part that the sample does a bad job of showing is where/when to call openTextDocument and showTextDocument and how the uri from the TextDocument Provider is piped into that.

In my case I have this:

```
activate {
        const provider = new customTextDocumentProvider(context.extensionPath);
	
        context.subscriptions.push(
		    vscode.workspace.registerTextDocumentContentProvider("textScheme", provider));


        vscode.workspace.openTextDocument(uri).then(doc => vscode.window.showTextDocument(doc));

}
export class customTextDocumentProvider implements vscode.TextDocumentContentProvider {
    static scheme = "textScheme";
   // skip some lines to keep this short.
provideTextDocumentContent(uri: vscode.Uri, token: vscode.CancellationToken): vscode.ProviderResult<string> {
        let text = "<p>oipjdfsijs</p>";
        return text ;
    }
}
```

edit:
My solution is:
```
const uri = vscode.Uri.parse("test").with({scheme:"m2cScheme"});
vscode.workspace.openTextDocument(uri).then(doc => vscode.window.showTextDocument(doc));
```

I didn't understand that the Uri.parse isn't a real url. It's creating a file using the input string.
Could put a comment there to show that.

**Comment by mjbvz** [comment] 2022-12-05 19:25
Closing as we will not prioritize this

If someone is interested in making this change, please first check with @jrieken to see if he'd accept a PR

**Closed by mjbvz** 2022-12-05 19:25 UTC

**Comment by betafcc** [comment] 2023-04-15 11:36
Just noticed this issue after spending a couple hours dissecting the example as well.

Now I feel the example itself is ok as it follows the general conventions on VSCode, the problem is that convention itself, as the verbose C#-style API is not very common in the TS/JS community

In fact even though I'm supposedly a senior, I was tripping investigating some stuff I didn't know if was important, like why it was setting an EventEmmiter if not explicitly used or why the provider was initialized as `new class implements vscode.TextDocumentContentProvider` instead of just, you know, a plain object

@mjbvz Are documentation contributions welcome?
