### ISSUE TITLE
Is there way to make MemFS have intellisense for js/ts files?

### ISSUE THREAD

**Issue by panlina** [microsoft/vscode-extension-samples#260] opened 2020-03-12 14:02 UTC
I tried this sample:
https://github.com/Microsoft/vscode-extension-samples/tree/master/fsprovider-sample

It's awesome but I find it lost intellisense for js/ts editing. Is it possible to make it work with intellisense in current vscode?

**Comment by mjbvz** [comment] 2020-03-13 19:12
Duplicate of #253

**Closed by mjbvz** 2020-03-13 19:12 UTC
