### ISSUE TITLE
hello-world-web-sample doesn't load if developing in WSL

### ISSUE THREAD

**Issue by cristian-spiescu** [microsoft/vscode-extension-samples#984] opened 2024-03-08 21:23 UTC
### Extension sample

hello-world-web-sample

### VS Code version

1.87.0

### What went wrong?

🙂: I checked out `hello-world-web-sample` in Windows, opened in VS Code and launched it. A new VS Code opens, and the extension works (i.e. I see the `Hello world` command in the command bar).

😢: I checked it out in WSL. I launch it from VS Code + WSL => A new VS Code opens (in Windows), but it doesn't load the extension.

Using `npm run run-in-browser` works.

Thanks in advance.

**Comment by cristian-spiescu** [comment] 2024-03-22 15:08
Does somebody have an idea? I'm wondering if: 
* it's something wrong on my side?
* this is a general issue? I.e. developing web extensions + WSL = no go
* if so, is this a regression, or this was always the case (and will be?)

**Comment by aeschli** [comment] 2024-04-09 08:14
We don't support developing web extensions in a remote extension host:
Duplicate of https://github.com/microsoft/vscode/issues/201069

**Closed by aeschli** 2024-04-09 08:14 UTC
