### ISSUE TITLE
List of problems I found in the samples.

### ISSUE THREAD

**Issue by x13machine** [Microsoft/vscode-extension-samples#174] opened 2019-04-16 10:55 UTC
I could probably fix most of them.

## progress-sample

1. `npm run compile` uses watch mode
2. uses 0.1.0 launch.json version
3. `Could not find the task 'tsc: watch - tsconfig.json'.` when running
4.  Second task is broken.
5.  .vscode-test should probably be added to .gitignore in my opinion.

## lsp-multi-server-sample

1. requires non-existent file /tsconfig.base.json to build.
2. `Could not find the task 'npm: watch:client'.` when trying to run.

## basic-multi-root-sample

1. `npm run compile` uses watch mode.
2. uses 0.1.0 launch.json version
3. `Could not find the task 'tsc: watch - tsconfig.json'.` when trying to run.

## fsprovider-sample

1. uses 0.1.0 launch.json version

## statusbar-sample

1. uses 0.1.0 launch.json version

## theme-sample

1. uses 0.1.0 launch.json version

## virtual-document-sample

1. uses 0.1.0 launch.json version
2. missing script compile

## webpack-sample

1. uses 0.1.0 launch.json version
2. missing script compile

## language-configuration-sample

1. missing script compile

## snippet-sample

1. missing script compile

## tree-view-sample

1. `error TS2345: Argument of type '{ focus: true; select: false; expand: boolean; }' is not assignable to parameter of type '{ select?: boolean; focus?: boolean; }'.` when building

## vim-sample

1. missing script compile

**Comment by octref** [comment] 2019-04-16 16:57
@x13machine Thanks for spotting the problems!

For language configuration sample and snippet sample, you don't have to compile anything, so there's no "script compile".

I fixed everything else except these 4 errors:

@bpasero progress-sample and basic-multi-root-sample seems to be caused by you moving to tasks 2.0. Can you take a look?

@dbaeumer Can you take a look at lsp-multi-server-sample?

@sandy081 Can you take a look at tree-view-sample?

**Comment by bpasero** [comment] 2019-04-16 17:06
> @bpasero progress-sample and basic-multi-root-sample seems to be caused by you moving to tasks 2.0. Can you take a look?

@dbaeumer do you have documentation how to update to Tasks 2.0? I am sorry, but my knowledge in that area is very limited 👍

**Comment by dbaeumer** [comment] 2019-04-18 07:31
Sure https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200

**Comment by dbaeumer** [comment] 2019-04-18 07:41
Fixed the issue in lsp-multi-server-sample.

**Comment by bpasero** [comment] 2019-04-18 08:09
Me too.

**Closed** 2019-04-18 16:28 UTC

**Comment by octref** [comment] 2019-04-18 16:29
@sandy081 I fixed that by updating vscode.d.ts to version 1.32.
