### ISSUE TITLE
Existing Chat-Sample based application is broken with version 1.90 (non-insiders build)

### ISSUE THREAD

**Issue by animeshj9** [microsoft/vscode-extension-samples#1048] opened 2024-06-10 06:43 UTC
### Extension sample

chat-sample

### VS Code version

1.90.0

### What went wrong?

We had a working chat-sample based extension on v1.89.0 on the main version of VSCode. Updating VSCode to 1.90 breaks the sample. The '@' command does not show up anymore with version 1.90.0.

Additionally, we used to add "enable-proposed-api": <our_extension_id> to the users argsv.json file on the users vscode to automatically enable the proposed API after getting confirmation from the user. That flow is also broken now.

**Comment by DinahK-2SO** [comment] 2024-06-11 06:56
To add more details, when developing extension on vscode v1.89.0, we added 2 proposed API files:
vscode.proposed.chatParticipant.d.ts, and vscode.proposed.languageModels.d.ts.

**Comment by DinahK-2SO** [comment] 2024-06-11 14:02
Find a possible solution: adding "chatParticipantPrivate" into the "enabledApiProposals" in package.json for VSCode >= 1.90

**Comment by erlingto** [comment] 2024-06-17 15:12
I'm also experiencing this issue. Does anyone know why the @participants have disappeared?

Is this feature not ready for publishing yet? I might have missed it, but the documentation doesn't clearly state that this feature is still in preview, if that's the case. Previously, the documentation mentioned to set a requirement for VSCode 1.90, which wasn't released yet and was only available through VSCode Insiders. I expected it to be available when 1.90 was released.

**Comment by bararchy** [comment] 2024-06-18 18:43
It seemed to just go even more broken now with even insider giving errors... I hope someone is looking into that

**Comment by isidorn** [comment] 2024-06-19 09:31
Sorry about the slow response here. 

@erlingto @DinahK-2SO @animeshj9 can you reproduce your issue with VS Code Insiders? If not - it is expected for VS Code Stable to silently ignore the participant contributions until the next stable release (first week of July). I apologize if this was not communicated clearly.

@bararchy can you provide those errors you are seeing now? The chat sample works fine for me with latest insiders. Might you have been hitting this issue that is now fixed https://github.com/microsoft/vscode/issues/216477

Also whenever you create an issue feel free to ping me @isidorn on it.
And I suggest always opening issues in https://github.com/microsoft/vscode/issues

**Comment by McNickSisto** [comment] 2024-06-20 22:35
upgraded to 1.9 and now it says "No chat models available"

**Comment by isidorn** [comment] 2024-06-21 09:15
@McNickSisto are you on latest VS Code Insiders and latest Copilot Chat pre-release? If yes and you still see this, are you using the vanilla chat sample? 
I just tried and it works for me.

**Comment by isidorn** [comment] 2024-06-21 09:42
No worries. That was an unexpected breakage - sorry!

Let's see if there is an issue that @McNickSisto is facing. If not, I will go ahead and close this issue.

**Comment by McNickSisto** [comment] 2024-06-21 14:57
@isidorn I checked again, I was in release version, i then switched to pre-release but I encountered the same error when calling the api.

![image](https://github.com/microsoft/vscode-extension-samples/assets/74677469/23538c88-11f5-4e85-878c-a54404d95847)

using the following
`    const models = await vscode.lm.selectChatModels({ vendor: 'copilot', family: 'gpt-3.5-turbo' });
`

**Comment by McNickSisto** [comment] 2024-06-21 15:05
@isidorn just realized I am not on VS Code Insiders, my bad.

**Comment by isidorn** [comment] 2024-06-21 15:29
Yes. Or you can use VS Code Insiders today.
I will go ahead and close this issue. Thanks!

**Closed by isidorn** 2024-06-21 15:29 UTC
