### ISSUE TITLE
Types for acquireVsCodeApi()

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-extension-samples#342] opened 2020-09-05 09:23 UTC
The page has `// @ts-check`, so it's spitting errors immediately

https://github.com/microsoft/vscode-extension-samples/blob/bb4a0c3a5dd9460a5cd64290b4d5c4f6bd79bdc4/webview-view-sample/media/main.js#L6

Would it be possible to add types for that?

It looks like it has 3 functions:

* getState: ƒ ()
* postMessage: ƒ (msg)
* setState: ƒ (newState)

Using something like this:

```js
/** @ts-ignore @type {{ getState: function():any, setState: function(any):void, postMessage: function(any):void }} */
const vscode = acquireVsCodeApi();
```

---

It looks like it's being used in more examples:

https://github.com/microsoft/vscode-extension-samples/blob/b153eeb993fa9b5c07ea4b4c1b8dddb24d443218/custom-editor-sample/media/catScratch.js#L9-L10

But it's just being told to suppress the error without adding any types.

**Comment by mjbvz** [comment] 2020-09-29 18:50
Duplicate of https://github.com/microsoft/vscode/issues/96221

**Closed by mjbvz** 2020-09-29 18:50 UTC
